name: findhome
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  flutter_svg: ^1.0.3
  pinput: ^1.2.2
  outline_gradient_button: ^2.0.0+1
  image_picker: ^0.8.4+8
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  flutter_spinkit: ^5.1.0
  get_storage: ^2.0.3
  dio: ^4.0.4
  http_parser: ^4.0.0
  cached_network_image: ^3.2.0
  geolocator: ^8.2.0
  geocoding: ^2.0.2
  permission_handler: ^9.1.0
  url_launcher: ^6.0.20
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: 8156907eecfa812b181a5a729d790f6d399f311b
  google_sign_in: ^5.2.4
  google_sign_in_web: ^0.10.0+5
  flutter_chat_bubble: ^2.0.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: AmstelvarAlpha
      fonts:
        - asset: assets/fonts/AmstelvarAlpha-VF.ttf
