// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxjfYkQ9jYM6Dhmg6qf1E9XW4SPoksFRw',
    appId: '1:1024369955634:web:3a45ac4befa529f2b9fd2b',
    messagingSenderId: '1024369955634',
    projectId: 'findhome-c26c5',
    authDomain: 'findhome-c26c5.firebaseapp.com',
    storageBucket: 'findhome-c26c5.appspot.com',
    measurementId: 'G-HVYNZDV6G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_yN3n2-JhPGbxUywWDG-ipmJzc9fxYrs',
    appId: '1:1024369955634:android:281d5f9f4bc137a4b9fd2b',
    messagingSenderId: '1024369955634',
    projectId: 'findhome-c26c5',
    storageBucket: 'findhome-c26c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4sYO4VVBIB_6Yr2aJX0vJscojme1mvlY',
    appId: '1:1024369955634:ios:cca0b2a96bacd68db9fd2b',
    messagingSenderId: '1024369955634',
    projectId: 'findhome-c26c5',
    storageBucket: 'findhome-c26c5.appspot.com',
    androidClientId: '1024369955634-h656fot9r90i6n3gcppvnh3rvtpg0bcg.apps.googleusercontent.com',
    iosClientId: '1024369955634-prpnrfkaj7tgbjiogmjah0am4ipdi4bj.apps.googleusercontent.com',
    iosBundleId: 'com.findhome.app',
  );
}
